# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19e67158957610e1c87f5a8a6b75173168eaf9a169d4d2c998712d284f796e52b985cbe4241a2b250f858d3393f88356c34c15da0702a284045eb8e1cef17ac9

test:
  secret_key_base: c3a4117c7b27ca01864e21c06e5f79c062adebd048df70427df89116f26d389a75cb4892a2fe2697d611226c1c9dc7c1ecab557d95c814493226ce4b58b68d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
